### ISSUE TITLE
Installation Directory?

### ISSUE THREAD

**Issue by countrymusicfy** [pachamaltese/jitsi-droplet#8]
In which directory do I run:  ./01_videoconf.sh

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dfear** [comment]
The directory is: /root

**Comment by countrymusicfy** [comment]
Thank you for the quick reply.  I log into root, enter ./01_videoconf.sh, and receive "No such file or directory"

**Comment by countrymusicfy** [comment]
Sorry, my oversight, I mistakenly installed an ubuntu server and not the jitsi server :)
